# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qtUI\mainInterFace.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 740)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 740))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("QTabBar::close-button{\n"
"    image: url(:/ico/Data/qrc/ico/close.png);\n"
"}\n"
"QTabBar::close-button:hover{\n"
"    image: url(:/ico/Data/qrc/ico/closed.png);\n"
"}")
        self.Main = QtWidgets.QWidget(MainWindow)
        self.Main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Main.setStyleSheet("#MainWindow{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"#Main{\n"
"    background-color: rgb(255,255,255);\n"
"    margin:10px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.Main.setObjectName("Main")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1181, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Interface = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Interface.setContentsMargins(10, 10, 10, 10)
        self.Interface.setSpacing(5)
        self.Interface.setObjectName("Interface")
        self.HeadToolBar = QtWidgets.QHBoxLayout()
        self.HeadToolBar.setSpacing(0)
        self.HeadToolBar.setObjectName("HeadToolBar")
        self.top_right = QtWidgets.QHBoxLayout()
        self.top_right.setSpacing(0)
        self.top_right.setObjectName("top_right")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(20, 20))
        self.graphicsView.setStyleSheet("border:none;\n"
"border-image: url(:/picture/Data/qrc/tetra.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.top_right.addWidget(self.graphicsView)
        self.EXETitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.EXETitle.setFont(font)
        self.EXETitle.setObjectName("EXETitle")
        self.top_right.addWidget(self.EXETitle)
        self.HeadToolBar.addLayout(self.top_right)
        spacerItem = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HeadToolBar.addItem(spacerItem)
        self.top_left = QtWidgets.QHBoxLayout()
        self.top_left.setSpacing(10)
        self.top_left.setObjectName("top_left")
        self.min_window = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.min_window.setMaximumSize(QtCore.QSize(24, 24))
        self.min_window.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min_window.setStyleSheet("#min_window{\n"
"    border-image: url(:/ico/Data/qrc/ico/min.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"#min_window:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/mined.png);\n"
"}")
        self.min_window.setObjectName("min_window")
        self.top_left.addWidget(self.min_window)
        self.max_window = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.max_window.setMaximumSize(QtCore.QSize(24, 24))
        self.max_window.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.max_window.setStyleSheet("#max_window{\n"
"    border-image: url(:/ico/Data/qrc/ico/max.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"#max_window:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/maxed.png);\n"
"}")
        self.max_window.setObjectName("max_window")
        self.top_left.addWidget(self.max_window)
        self.close_window = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.close_window.setMaximumSize(QtCore.QSize(24, 24))
        self.close_window.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_window.setStyleSheet("#close_window{\n"
"    border-image: url(:/ico/Data/qrc/ico/close.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"#close_window:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/closed.png)\n"
"}")
        self.close_window.setObjectName("close_window")
        self.top_left.addWidget(self.close_window)
        self.HeadToolBar.addLayout(self.top_left)
        self.HeadToolBar.setStretch(0, 1)
        self.HeadToolBar.setStretch(2, 1)
        self.Interface.addLayout(self.HeadToolBar)
        self.ContentTabList = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.ContentTabList.setMaximumSize(QtCore.QSize(1160, 660))
        self.ContentTabList.setStyleSheet("QPushButton{\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"}")
        self.ContentTabList.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.ContentTabList.setTabsClosable(True)
        self.ContentTabList.setObjectName("ContentTabList")
        self.HomeTab = QtWidgets.QWidget()
        self.HomeTab.setToolTip("")
        self.HomeTab.setObjectName("HomeTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.HomeTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1151, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_2.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 441, 301))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setHorizontalSpacing(22)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.musicControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.musicControler.setMinimumSize(QtCore.QSize(64, 64))
        self.musicControler.setMaximumSize(QtCore.QSize(64, 64))
        self.musicControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.musicControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/ico/Data/qrc/ico/music.png);\n"
"}")
        self.musicControler.setText("")
        self.musicControler.setObjectName("musicControler")
        self.verticalLayout_13.addWidget(self.musicControler)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 2, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.levelControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.levelControler.setMinimumSize(QtCore.QSize(64, 64))
        self.levelControler.setMaximumSize(QtCore.QSize(64, 64))
        self.levelControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.levelControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/ico/Data/qrc/ico/level.png);\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/leveled.png);\n"
"}")
        self.levelControler.setText("")
        self.levelControler.setObjectName("levelControler")
        self.verticalLayout_10.addWidget(self.levelControler)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 0, 3, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.monsterControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.monsterControler.setMinimumSize(QtCore.QSize(64, 64))
        self.monsterControler.setMaximumSize(QtCore.QSize(64, 64))
        self.monsterControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.monsterControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/picture/Data/qrc/Monster.png);\n"
"}")
        self.monsterControler.setText("")
        self.monsterControler.setObjectName("monsterControler")
        self.verticalLayout_11.addWidget(self.monsterControler)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 1, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.EquipmentControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.EquipmentControler.setMinimumSize(QtCore.QSize(64, 64))
        self.EquipmentControler.setMaximumSize(QtCore.QSize(64, 64))
        self.EquipmentControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EquipmentControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/picture/Data/qrc/Equipment.png);\n"
"}")
        self.EquipmentControler.setText("")
        self.EquipmentControler.setObjectName("EquipmentControler")
        self.verticalLayout_6.addWidget(self.EquipmentControler)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 2, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SuppliesControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.SuppliesControler.setMinimumSize(QtCore.QSize(64, 64))
        self.SuppliesControler.setMaximumSize(QtCore.QSize(64, 64))
        self.SuppliesControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SuppliesControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/picture/Data/qrc/Supplies.png);\n"
"}")
        self.SuppliesControler.setText("")
        self.SuppliesControler.setObjectName("SuppliesControler")
        self.verticalLayout_7.addWidget(self.SuppliesControler)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_8.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.FollowerControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.FollowerControler.setMinimumSize(QtCore.QSize(64, 64))
        self.FollowerControler.setMaximumSize(QtCore.QSize(64, 64))
        self.FollowerControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FollowerControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/picture/Data/qrc/Follower.png);\n"
"}")
        self.FollowerControler.setText("")
        self.FollowerControler.setObjectName("FollowerControler")
        self.verticalLayout_9.addWidget(self.FollowerControler)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 1, 1, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.effectControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.effectControler.setMinimumSize(QtCore.QSize(64, 64))
        self.effectControler.setMaximumSize(QtCore.QSize(64, 64))
        self.effectControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.effectControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/ico/Data/qrc/ico/special Effect.png);\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/special Effected.png);\n"
"}")
        self.effectControler.setText("")
        self.effectControler.setObjectName("effectControler")
        self.verticalLayout_14.addWidget(self.effectControler)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.gridLayout_2.addLayout(self.verticalLayout_14, 2, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MagicaVoxel = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.MagicaVoxel.setMinimumSize(QtCore.QSize(64, 64))
        self.MagicaVoxel.setMaximumSize(QtCore.QSize(64, 64))
        self.MagicaVoxel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MagicaVoxel.setStyleSheet("QPushButton{\n"
"    border-image: url(:/picture/Data/qrc/MagicaVoxel.png);\n"
"}")
        self.MagicaVoxel.setText("")
        self.MagicaVoxel.setObjectName("MagicaVoxel")
        self.verticalLayout_2.addWidget(self.MagicaVoxel)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CharacterControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.CharacterControler.setMinimumSize(QtCore.QSize(64, 64))
        self.CharacterControler.setMaximumSize(QtCore.QSize(64, 64))
        self.CharacterControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CharacterControler.setToolTipDuration(-10)
        self.CharacterControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/picture/Data/qrc/CharacterControler.png);\n"
"}")
        self.CharacterControler.setText("")
        self.CharacterControler.setObjectName("CharacterControler")
        self.verticalLayout.addWidget(self.CharacterControler)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stageControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.stageControler.setMinimumSize(QtCore.QSize(64, 64))
        self.stageControler.setMaximumSize(QtCore.QSize(64, 64))
        self.stageControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stageControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/ico/Data/qrc/ico/stage.png);\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/staged.png);\n"
"}")
        self.stageControler.setText("")
        self.stageControler.setObjectName("stageControler")
        self.verticalLayout_4.addWidget(self.stageControler)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.NPCControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.NPCControler.setMinimumSize(QtCore.QSize(64, 64))
        self.NPCControler.setMaximumSize(QtCore.QSize(64, 64))
        self.NPCControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NPCControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/picture/Data/qrc/NPC.png);\n"
"}")
        self.NPCControler.setText("")
        self.NPCControler.setObjectName("NPCControler")
        self.verticalLayout_3.addWidget(self.NPCControler)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3.setMaximumSize(QtCore.QSize(64, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stageControler_6 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.stageControler_6.setMinimumSize(QtCore.QSize(64, 64))
        self.stageControler_6.setMaximumSize(QtCore.QSize(64, 64))
        self.stageControler_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stageControler_6.setStyleSheet("QPushButton{\n"
"    border-image: url(:/ico/Data/qrc/ico/plot.png);\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/ploted.png);\n"
"}")
        self.stageControler_6.setText("")
        self.stageControler_6.setObjectName("stageControler_6")
        self.verticalLayout_15.addWidget(self.stageControler_6)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_15.addWidget(self.label_16)
        self.gridLayout_2.addLayout(self.verticalLayout_15, 0, 4, 1, 1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.achievementControler = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.achievementControler.setMinimumSize(QtCore.QSize(64, 64))
        self.achievementControler.setMaximumSize(QtCore.QSize(64, 64))
        self.achievementControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.achievementControler.setStyleSheet("QPushButton{\n"
"    border-image: url(:/ico/Data/qrc/ico/achievement.png);\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/achievemented.png);\n"
"}")
        self.achievementControler.setText("")
        self.achievementControler.setObjectName("achievementControler")
        self.verticalLayout_17.addWidget(self.achievementControler)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_17.addWidget(self.label_18)
        self.gridLayout_2.addLayout(self.verticalLayout_17, 2, 4, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.stageControler_7 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.stageControler_7.setMinimumSize(QtCore.QSize(64, 64))
        self.stageControler_7.setMaximumSize(QtCore.QSize(64, 64))
        self.stageControler_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stageControler_7.setStyleSheet("QPushButton{\n"
"    border-image: url(:/picture/Data/qrc/Tield.png);\n"
"}")
        self.stageControler_7.setText("")
        self.stageControler_7.setObjectName("stageControler_7")
        self.verticalLayout_16.addWidget(self.stageControler_7)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_16.addWidget(self.label_17)
        self.gridLayout_2.addLayout(self.verticalLayout_16, 1, 3, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.stageControler_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.stageControler_3.setMinimumSize(QtCore.QSize(64, 64))
        self.stageControler_3.setMaximumSize(QtCore.QSize(64, 64))
        self.stageControler_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stageControler_3.setStyleSheet("QPushButton{\n"
"    border-image: url(:/ico/Data/qrc/ico/grade.png);\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/graded.png);\n"
"}")
        self.stageControler_3.setText("")
        self.stageControler_3.setObjectName("stageControler_3")
        self.verticalLayout_12.addWidget(self.stageControler_3)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 1, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 1, 1, 1)
        self.OnlineServer = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.OnlineServer.setMinimumSize(QtCore.QSize(0, 136))
        self.OnlineServer.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.OnlineServer.setStyleSheet("QPushButton{\n"
"    background-image: url(:/picture/Data/qrc/server.png);\n"
"}")
        self.OnlineServer.setText("")
        self.OnlineServer.setObjectName("OnlineServer")
        self.gridLayout_4.addWidget(self.OnlineServer, 2, 1, 1, 1)
        self.CommandList = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CommandList.setMinimumSize(QtCore.QSize(0, 136))
        self.CommandList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CommandList.setStyleSheet("QPushButton{\n"
"    background-image: url(:/picture/Data/qrc/command.png);\n"
"}")
        self.CommandList.setText("")
        self.CommandList.setObjectName("CommandList")
        self.gridLayout_4.addWidget(self.CommandList, 0, 1, 1, 1)
        self.OnlineStore = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.OnlineStore.setMinimumSize(QtCore.QSize(0, 136))
        self.OnlineStore.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.OnlineStore.setStyleSheet("QPushButton{\n"
"    background-image: url(:/picture/Data/qrc/store.png);\n"
"}")
        self.OnlineStore.setText("")
        self.OnlineStore.setObjectName("OnlineStore")
        self.gridLayout_4.addWidget(self.OnlineStore, 2, 0, 1, 1)
        self.CardControler = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CardControler.setMinimumSize(QtCore.QSize(0, 136))
        self.CardControler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CardControler.setStyleSheet("QPushButton{\n"
"    background-image: url(:/picture/Data/qrc/cardPkg.png);\n"
"}")
        self.CardControler.setText("")
        self.CardControler.setObjectName("CardControler")
        self.gridLayout_4.addWidget(self.CardControler, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.gridLayout.addLayout(self.formLayout, 0, 2, 2, 1)
        self.widget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget.setStyleSheet("#userSetting{\n"
"    border-image: url(:/ico/Data/qrc/ico/set.png);\n"
"}\n"
"#userSetting:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/seted.png);\n"
"}\n"
"#userData{\n"
"    border-image: url(:/ico/Data/qrc/ico/user.png);\n"
"}\n"
"#userData:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/usered.png);\n"
"}\n"
"#userLogin{\n"
"    border-image: url(:/ico/Data/qrc/ico/login.png);\n"
"}\n"
"#userLogin:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/logined.png);\n"
"}\n"
"#userLogout{\n"
"    border-image: url(:/ico/Data/qrc/ico/logout.png);\n"
"}\n"
"#userLogout:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/logouted.png);\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 445, 302))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.userLogin = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.userLogin.setMinimumSize(QtCore.QSize(64, 64))
        self.userLogin.setMaximumSize(QtCore.QSize(64, 64))
        self.userLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.userLogin.setText("")
        self.userLogin.setObjectName("userLogin")
        self.gridLayout_3.addWidget(self.userLogin, 2, 0, 1, 1)
        self.userLogout = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.userLogout.setMinimumSize(QtCore.QSize(64, 64))
        self.userLogout.setMaximumSize(QtCore.QSize(64, 64))
        self.userLogout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.userLogout.setText("")
        self.userLogout.setObjectName("userLogout")
        self.gridLayout_3.addWidget(self.userLogout, 2, 1, 1, 1)
        self.userData = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.userData.setMinimumSize(QtCore.QSize(64, 64))
        self.userData.setMaximumSize(QtCore.QSize(64, 64))
        self.userData.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.userData.setText("")
        self.userData.setObjectName("userData")
        self.gridLayout_3.addWidget(self.userData, 1, 0, 1, 1)
        self.userSetting = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.userSetting.setMinimumSize(QtCore.QSize(64, 64))
        self.userSetting.setMaximumSize(QtCore.QSize(64, 64))
        self.userSetting.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.userSetting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.userSetting.setText("")
        self.userSetting.setObjectName("userSetting")
        self.gridLayout_3.addWidget(self.userSetting, 0, 0, 1, 1)
        self.xxxxx = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.xxxxx.setMinimumSize(QtCore.QSize(64, 64))
        self.xxxxx.setMaximumSize(QtCore.QSize(64, 64))
        self.xxxxx.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.xxxxx.setText("")
        self.xxxxx.setObjectName("xxxxx")
        self.gridLayout_3.addWidget(self.xxxxx, 2, 2, 1, 1)
        self.xxxxx_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.xxxxx_2.setMinimumSize(QtCore.QSize(64, 64))
        self.xxxxx_2.setMaximumSize(QtCore.QSize(64, 64))
        self.xxxxx_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.xxxxx_2.setText("")
        self.xxxxx_2.setObjectName("xxxxx_2")
        self.gridLayout_3.addWidget(self.xxxxx_2, 2, 3, 1, 1)
        self.simpleData = QtWidgets.QVBoxLayout()
        self.simpleData.setSpacing(0)
        self.simpleData.setObjectName("simpleData")
        self.ModName = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.ModName.setFont(font)
        self.ModName.setObjectName("ModName")
        self.simpleData.addWidget(self.ModName)
        self.UserName = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.UserName.setFont(font)
        self.UserName.setObjectName("UserName")
        self.simpleData.addWidget(self.UserName)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GamePath = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.GamePath.setFont(font)
        self.GamePath.setObjectName("GamePath")
        self.horizontalLayout_2.addWidget(self.GamePath)
        self.sel_GamePath = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sel_GamePath.setMinimumSize(QtCore.QSize(20, 20))
        self.sel_GamePath.setMaximumSize(QtCore.QSize(20, 20))
        self.sel_GamePath.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sel_GamePath.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(170, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 255);\n"
"}")
        self.sel_GamePath.setText("")
        self.sel_GamePath.setObjectName("sel_GamePath")
        self.horizontalLayout_2.addWidget(self.sel_GamePath)
        self.simpleData.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.gridLayoutWidget_2)
        self.graphicsView_3.setMaximumSize(QtCore.QSize(32, 32))
        self.graphicsView_3.setStyleSheet("border-image: url(:/picture/Data/qrc/tetra.png);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.horizontalLayout.addWidget(self.graphicsView_3)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.simpleData.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.textBrowser.setObjectName("textBrowser")
        self.simpleData.addWidget(self.textBrowser)
        self.gridLayout_3.addLayout(self.simpleData, 0, 1, 2, 3)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 4)
        self.gridLayout.setColumnStretch(2, 3)
        self.ContentTabList.addTab(self.HomeTab, "")
        self.Interface.addWidget(self.ContentTabList)
        self.Interface.setStretch(1, 1)
        MainWindow.setCentralWidget(self.Main)

        self.retranslateUi(MainWindow)
        self.ContentTabList.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AL-IDE"))
        self.EXETitle.setText(_translate("MainWindow", "AL-IDE_1.0.0.0"))
        self.min_window.setToolTip(_translate("MainWindow", "<html><head/><body><p>最小化</p></body></html>"))
        self.min_window.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.max_window.setToolTip(_translate("MainWindow", "<html><head/><body><p>最大化</p></body></html>"))
        self.max_window.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.close_window.setToolTip(_translate("MainWindow", "<html><head/><body><p>关闭</p></body></html>"))
        self.close_window.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.HomeTab.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.musicControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>音乐系统</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "音乐系统"))
        self.levelControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>关卡管理</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "关卡管理"))
        self.monsterControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>怪物系统</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "怪物系统"))
        self.EquipmentControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>装备系统</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "装备系统"))
        self.SuppliesControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>物资系统</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "物资系统"))
        self.FollowerControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>随从系统</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "随从系统"))
        self.effectControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>特效系统</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "特效系统"))
        self.MagicaVoxel.setToolTip(_translate("MainWindow", "<html><head/><body><p>场景制作</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "场景制作"))
        self.CharacterControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>角色系统</p></body></html>"))
        self.label.setText(_translate("MainWindow", "角色系统"))
        self.stageControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>场景管理</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "场景管理"))
        self.NPCControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>NPC系统</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "NPC系统"))
        self.stageControler_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>剧情系统</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "剧本系统"))
        self.achievementControler.setToolTip(_translate("MainWindow", "<html><head/><body><p>成就系统</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "成就系统"))
        self.stageControler_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Tield</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "关卡编辑器"))
        self.stageControler_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>等级系统</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "等级系统"))
        self.label_9.setText(_translate("MainWindow", "指令管理"))
        self.label_6.setText(_translate("MainWindow", "卡牌管理"))
        self.label_19.setText(_translate("MainWindow", "卡牌集市"))
        self.label_20.setText(_translate("MainWindow", "联机大厅"))
        self.userData.setToolTip(_translate("MainWindow", "<html><head/><body><p>我的</p></body></html>"))
        self.userSetting.setToolTip(_translate("MainWindow", "<html><head/><body><p>设置</p></body></html>"))
        self.ModName.setToolTip(_translate("MainWindow", "<html><head/><body><p>模组名</p></body></html>"))
        self.ModName.setText(_translate("MainWindow", "*Mod"))
        self.UserName.setToolTip(_translate("MainWindow", "<html><head/><body><p>用户名</p></body></html>"))
        self.UserName.setText(_translate("MainWindow", "无名"))
        self.GamePath.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.GamePath.setText(_translate("MainWindow", "D:"))
        self.sel_GamePath.setToolTip(_translate("MainWindow", "<html><head/><body><p>设置游戏本体路径</p></body></html>"))
        self.label_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>原石积分</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "∞"))
        self.ContentTabList.setTabText(self.ContentTabList.indexOf(self.HomeTab), _translate("MainWindow", "主页"))
from . import AL_IDE_MainInterFace_rc
