# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qtUI\CardControler\cardSimpleItemModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(320, 130)
        main.setMinimumSize(QtCore.QSize(320, 130))
        main.setStyleSheet("#main{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.item = QtWidgets.QWidget(main)
        self.item.setGeometry(QtCore.QRect(5, 5, 310, 120))
        self.item.setMinimumSize(QtCore.QSize(310, 120))
        self.item.setStyleSheet("#item{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.item.setObjectName("item")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.item)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 311, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cardArt = WidgetToolTipWidget(self.horizontalLayoutWidget)
        self.cardArt.setMinimumSize(QtCore.QSize(48, 48))
        self.cardArt.setMaximumSize(QtCore.QSize(48, 48))
        self.cardArt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cardArt.setToolTip("")
        self.cardArt.setStyleSheet("#cardArt{border-image: url(:/picture/Data/qrc/Unknown.png);}")
        self.cardArt.setText("")
        self.cardArt.setAlignment(QtCore.Qt.AlignCenter)
        self.cardArt.setObjectName("cardArt")
        self.horizontalLayout_5.addWidget(self.cardArt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.cardId = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cardId.setMinimumSize(QtCore.QSize(80, 0))
        self.cardId.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.cardId.setFont(font)
        self.cardId.setAlignment(QtCore.Qt.AlignCenter)
        self.cardId.setObjectName("cardId")
        self.verticalLayout_2.addWidget(self.cardId)
        self.cardName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cardName.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.cardName.setFont(font)
        self.cardName.setAlignment(QtCore.Qt.AlignCenter)
        self.cardName.setObjectName("cardName")
        self.verticalLayout_2.addWidget(self.cardName)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#cardSelect{\n"
"    border-image: url(:/ico/Data/qrc/ico/select.png);\n"
"}\n"
"#cardEdit{\n"
"    border-image: url(:/ico/Data/qrc/ico/edit.png);\n"
"}\n"
"#cardEdit:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/edited.png);\n"
"}\n"
"#cardExport{\n"
"    border-image: url(:/ico/Data/qrc/ico/export.png);\n"
"}\n"
"#cardExport:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/exported.png);\n"
"}\n"
"#cardImport{\n"
"    border-image: url(:/ico/Data/qrc/ico/import.png);\n"
"}\n"
"#cardImport:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/imported.png);\n"
"}\n"
"#cardPrint{\n"
"    border-image: url(:/ico/Data/qrc/ico/print.png);\n"
"}\n"
"#cardPrint:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/printed.png);\n"
"}\n"
"#cardRelease{\n"
"    border-image: url(:/ico/Data/qrc/ico/release.png);\n"
"}\n"
"#cardRelease:hover{\n"
"    border-image: url(:/ico/Data/qrc/ico/released.png);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 212, 84))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cardSelect = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cardSelect.setMinimumSize(QtCore.QSize(30, 30))
        self.cardSelect.setMaximumSize(QtCore.QSize(30, 30))
        self.cardSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cardSelect.setStyleSheet("")
        self.cardSelect.setText("")
        self.cardSelect.setObjectName("cardSelect")
        self.horizontalLayout_3.addWidget(self.cardSelect)
        self.cardEdit = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cardEdit.setMinimumSize(QtCore.QSize(30, 30))
        self.cardEdit.setMaximumSize(QtCore.QSize(30, 30))
        self.cardEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cardEdit.setText("")
        self.cardEdit.setObjectName("cardEdit")
        self.horizontalLayout_3.addWidget(self.cardEdit)
        self.cardExport = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cardExport.setMinimumSize(QtCore.QSize(30, 30))
        self.cardExport.setMaximumSize(QtCore.QSize(30, 30))
        self.cardExport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cardExport.setText("")
        self.cardExport.setObjectName("cardExport")
        self.horizontalLayout_3.addWidget(self.cardExport)
        self.cardImport = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cardImport.setMinimumSize(QtCore.QSize(30, 30))
        self.cardImport.setMaximumSize(QtCore.QSize(30, 30))
        self.cardImport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cardImport.setText("")
        self.cardImport.setObjectName("cardImport")
        self.horizontalLayout_3.addWidget(self.cardImport)
        self.cardPrint = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cardPrint.setMinimumSize(QtCore.QSize(30, 30))
        self.cardPrint.setMaximumSize(QtCore.QSize(30, 30))
        self.cardPrint.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cardPrint.setText("")
        self.cardPrint.setObjectName("cardPrint")
        self.horizontalLayout_3.addWidget(self.cardPrint)
        self.cardRelease = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.cardRelease.setMinimumSize(QtCore.QSize(30, 30))
        self.cardRelease.setMaximumSize(QtCore.QSize(30, 30))
        self.cardRelease.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.cardRelease.setText("")
        self.cardRelease.setObjectName("cardRelease")
        self.horizontalLayout_3.addWidget(self.cardRelease)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.description = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        self.description.setMinimumSize(QtCore.QSize(210, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.description.setFont(font)
        self.description.setStyleSheet("QTextBrowser{\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}")
        self.description.setObjectName("description")
        self.verticalLayout_3.addWidget(self.description)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    padding:3px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsView_2.setMaximumSize(QtCore.QSize(24, 24))
        self.graphicsView_2.setStyleSheet("border-image: url(:/picture/Data/qrc/tetra.png);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.horizontalLayout_4.addWidget(self.graphicsView_2)
        self.price = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(9)
        self.price.setFont(font)
        self.price.setStyleSheet("QLabel{\n"
"    padding:3px;\n"
"}")
        self.price.setObjectName("price")
        self.horizontalLayout_4.addWidget(self.price)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.cardId.setText(_translate("main", "ID:10001"))
        self.cardName.setText(_translate("main", "无名"))
        self.cardSelect.setToolTip(_translate("main", "<html><head/><body><p>选择卡牌</p></body></html>"))
        self.cardEdit.setToolTip(_translate("main", "<html><head/><body><p>编辑卡牌</p></body></html>"))
        self.cardExport.setToolTip(_translate("main", "<html><head/><body><p>导出卡牌</p></body></html>"))
        self.cardImport.setToolTip(_translate("main", "<html><head/><body><p>导入卡牌</p></body></html>"))
        self.cardPrint.setToolTip(_translate("main", "<html><head/><body><p>在游戏中印卡</p></body></html>"))
        self.cardRelease.setToolTip(_translate("main", "<html><head/><body><p>发布</p></body></html>"))
        self.description.setHtml(_translate("main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe 黑体 Std R\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">还没有介绍哦~</p></body></html>"))
        self.label_2.setText(_translate("main", "标准卡包"))
        self.price.setText(_translate("main", "∞"))
from ..MyWidgets.WidgetToolTipWidget import WidgetToolTipWidget
from .. import AL_IDE_MainInterFace_rc
